# ------------------------------------------------------------------------------
# More resources related to this file:
# [1] Overview   | https://docs.docker.com/compose/
# [2] PostgreSQL | https://github.com/docker-library/docs/tree/master/postgres
# [3] Node.js    | https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image
# -------------
#  More resources for your projects:
# [4] Samples    | https://github.com/docker/awesome-compose
# [5] Env Vars   | https://docs.docker.com/compose/environment-variables/
# [6] Secrets    | https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
# ------------------------------------------------------------------------------

services:
  #heroku-cli:
  #  build: ./heroku
  # env_file: ./heroku/.env
  db:
    image: postgres
    #build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Neverquit4405!
      POSTGRES_DB: audio_db
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./db/init_data:/docker-entrypoint-initdb.d
      - audioProject-db:/var/lib/postgresql/data  
  web:
    #build: 
    #  context: ./
    #  dockerfile: Dockerfile
    #  target: devapp
    image: node:12
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - db                                      
    env_file: .env
    ports:
        - "5432:5432" 
    volumes:
    #  - ./src:/app/src
      - ./:/home/node/app
    command: "npm start"

volumes:
  audioProject-db: {}
